[package]
name = "petunia_render_gl"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
petunia_core = { workspace = true }
petunia_config = { workspace = true }
petunia_mesh = { workspace = true }
petunia_render = { workspace = true }
egui_glow = { workspace = true }
glam = { workspace = true }
bytemuck = "1"
uuid = { workspace = true }
petunia_project = { workspace = true }
winit = "0.30"
glutin = "0.32"
glutin-winit = "0.5"
raw-window-handle = "0.6"
