[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
petunia_core = { workspace = true }
petunia_config = { workspace = true }
petunia_project = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
