// Auto-generated by scripts/migrate_bible_to_docs.py
export default [
  {
    "text": "Visão Geral da Bíblia",
    "items": [
      {
        "text": "Portal & Índice Geral",
        "link": "/bible/"
      }
    ]
  },
  {
    "text": "Constituição & Diretivas (00-16)",
    "collapsed": true,
    "items": [
      {
        "text": "00 — Constituição do Projeto e Diretiva para Agentes",
        "link": "/bible/constitution/00-constituicao-do-projeto-e-diretiva-para-agent"
      },
      {
        "text": "01 — Protocolo de Especificação P3D e Prompt para LLM",
        "link": "/bible/constitution/01-protocolo-de-especificacao-p3d-e-prompt-para"
      },
      {
        "text": "02 — Gauntlet Loop, Quality Gates e Definition of Done",
        "link": "/bible/constitution/02-gauntlet-loop-quality-gates-e-definition-of"
      },
      {
        "text": "03 — Invariantes de UI/UX, Design System e Acessibilidade",
        "link": "/bible/constitution/03-invariantes-de-ui-ux-design-system-e-acessib"
      },
      {
        "text": "04 — Invariantes de Arquitetura, Modularidade e Core Agnóstico à UI",
        "link": "/bible/constitution/04-invariantes-de-arquitetura-modularidade-e-co"
      },
      {
        "text": "05 — Política de Documentação, Screenshots e Changelog",
        "link": "/bible/constitution/05-politica-de-documentacao-screenshots-e-chang"
      },
      {
        "text": "06 — Governança do Backlog, Status e Prioridades",
        "link": "/bible/constitution/06-governanca-do-backlog-status-e-prioridades"
      },
      {
        "text": "07 — Roadmap, Adendos e Critérios para Novos Módulos",
        "link": "/bible/constitution/07-roadmap-adendos-e-criterios-para-novos-modul"
      },
      {
        "text": "08 — Roadmap Pós-GA Aprovado",
        "link": "/bible/constitution/08-roadmap-pos-ga-aprovado"
      },
      {
        "text": "09 — Shared 3D Foundation, Map Editor e Game Engine",
        "link": "/bible/constitution/09-shared-3d-foundation-map-editor-e-game-engin"
      },
      {
        "text": "10 — Convenções Espaciais, Unidades e Coordenadas",
        "link": "/bible/constitution/10-convencoes-espaciais-unidades-e-coordenadas"
      },
      {
        "text": "11 — Contrato de Mesh, Selection, Tools e Undo",
        "link": "/bible/constitution/11-contrato-de-mesh-selection-tools-e-undo"
      },
      {
        "text": "12 — Contrato de Materiais, Texturas, UV e Color Pipeline",
        "link": "/bible/constitution/12-contrato-de-materiais-texturas-uv-e-color-p"
      },
      {
        "text": "13 — Jobs, Concorrência, Diagnósticos, Segurança e Trust Boundaries",
        "link": "/bible/constitution/13-jobs-concorrencia-diagnosticos-seguranca-e"
      },
      {
        "text": "14 — Release, Compatibilidade, Distribuição e Critérios de GA",
        "link": "/bible/constitution/14-release-compatibilidade-distribuicao-e-crit"
      },
      {
        "text": "15 — Auditoria Final de Lacunas e Readiness Matrix",
        "link": "/bible/constitution/15-auditoria-final-de-lacunas-e-readiness-matrix"
      },
      {
        "text": "16 — Master Prompt de Implementação por Gauntlet Waves",
        "link": "/bible/constitution/16-master-prompt-de-implementacao-por-gauntlet-w"
      }
    ]
  },
  {
    "text": "Seções Macro (A a O)",
    "collapsed": true,
    "items": [
      {
        "text": "A — Project & Files",
        "link": "/bible/sections/section-a-project-files"
      },
      {
        "text": "B — Viewport & Navigation",
        "link": "/bible/sections/section-b-viewport-navigation"
      },
      {
        "text": "C — Reference Workflow",
        "link": "/bible/sections/section-c-reference-workflow"
      },
      {
        "text": "D — Selection, Transform & Modeling",
        "link": "/bible/sections/section-d-selection-transform-modeling"
      },
      {
        "text": "E — Assets, Scene & Inspector",
        "link": "/bible/sections/section-e-assets-scene-inspector"
      },
      {
        "text": "F — Surface, Materials, Paint & UV",
        "link": "/bible/sections/section-f-surface-materials-paint-uv"
      },
      {
        "text": "G — Animation & Rigging",
        "link": "/bible/sections/section-g-animation-rigging"
      },
      {
        "text": "H — Import & Export",
        "link": "/bible/sections/section-h-import-export"
      },
      {
        "text": "I — UI Shell & Professional UX",
        "link": "/bible/sections/section-i-ui-shell-professional-ux"
      },
      {
        "text": "J — Customization, i18n & Keymaps",
        "link": "/bible/sections/section-j-customization-i18n-keymaps"
      },
      {
        "text": "K — Architecture & Modularity",
        "link": "/bible/sections/section-k-architecture-modularity"
      },
      {
        "text": "L — Plugins, Automation & AI",
        "link": "/bible/sections/section-l-plugins-automation-ai"
      },
      {
        "text": "M — Help, Documentation & QA",
        "link": "/bible/sections/section-m-help-documentation-qa"
      },
      {
        "text": "N — Performance & Project Philosophy",
        "link": "/bible/sections/section-n-performance-project-philosophy"
      },
      {
        "text": "O — Future Product Integration",
        "link": "/bible/sections/section-o-future-product-integration"
      }
    ]
  },
  {
    "text": "P3D: Waves 0 a 6 (Implementadas)",
    "collapsed": true,
    "items": [
      {
        "text": "P3D-001 — Sistema de Projetos",
        "link": "/bible/specs/p3d-001-sistema-de-projetos"
      },
      {
        "text": "P3D-002 — Autosave e Recuperação",
        "link": "/bible/specs/p3d-002-autosave-e-recuperacao"
      },
      {
        "text": "P3D-003 — Biblioteca de Modelos por Projeto",
        "link": "/bible/specs/p3d-003-biblioteca-de-modelos-por-projeto"
      },
      {
        "text": "P3D-004 — Viewport 3D",
        "link": "/bible/specs/p3d-004-viewport-3d"
      },
      {
        "text": "P3D-005 — Navegação 3D",
        "link": "/bible/specs/p3d-005-navegacao-3d"
      },
      {
        "text": "P3D-006 — Vistas ortográficas",
        "link": "/bible/specs/p3d-006-vistas-ortograficas"
      },
      {
        "text": "P3D-007 — Navigation Gizmo",
        "link": "/bible/specs/p3d-007-navigation-gizmo"
      },
      {
        "text": "P3D-008 — Frame Selected / Frame All",
        "link": "/bible/specs/p3d-008-frame-selected-frame-all"
      },
      {
        "text": "P3D-009 — Grid 3D",
        "link": "/bible/specs/p3d-009-grid-3d"
      },
      {
        "text": "P3D-010 — Overlays",
        "link": "/bible/specs/p3d-010-overlays"
      },
      {
        "text": "P3D-011 — X-Ray",
        "link": "/bible/specs/p3d-011-x-ray"
      },
      {
        "text": "P3D-012 — Shading Modes",
        "link": "/bible/specs/p3d-012-shading-modes"
      },
      {
        "text": "P3D-013 — Imagens de referência",
        "link": "/bible/specs/p3d-013-imagens-de-referencia"
      },
      {
        "text": "P3D-014 — Referências ortográficas",
        "link": "/bible/specs/p3d-014-referencias-ortograficas"
      },
      {
        "text": "P3D-015 — Object Mode / Modelo Unificado de Seleção",
        "link": "/bible/specs/p3d-015-object-mode-modelo-unificado-de-selecao"
      },
      {
        "text": "P3D-016 — Edit Mode — absorvido por P3D-015",
        "link": "/bible/specs/p3d-016-edit-mode-absorvido-por-p3d-015"
      },
      {
        "text": "P3D-017 — Vertex Select",
        "link": "/bible/specs/p3d-017-vertex-select"
      },
      {
        "text": "P3D-018 — Edge Select",
        "link": "/bible/specs/p3d-018-edge-select"
      },
      {
        "text": "P3D-019 — Face Select",
        "link": "/bible/specs/p3d-019-face-select"
      },
      {
        "text": "P3D-020 — Object Selection",
        "link": "/bible/specs/p3d-020-object-selection"
      },
      {
        "text": "P3D-021 — Move",
        "link": "/bible/specs/p3d-021-move"
      },
      {
        "text": "P3D-022 — Rotate",
        "link": "/bible/specs/p3d-022-rotate"
      },
      {
        "text": "P3D-023 — Scale",
        "link": "/bible/specs/p3d-023-scale"
      },
      {
        "text": "P3D-024 — Universal Transform",
        "link": "/bible/specs/p3d-024-universal-transform"
      },
      {
        "text": "P3D-025 — Axis Constraints",
        "link": "/bible/specs/p3d-025-axis-constraints"
      },
      {
        "text": "P3D-026 — Transform Orientation",
        "link": "/bible/specs/p3d-026-transform-orientation"
      },
      {
        "text": "P3D-027 — Pivot System",
        "link": "/bible/specs/p3d-027-pivot-system"
      },
      {
        "text": "P3D-028 — Add Primitives",
        "link": "/bible/specs/p3d-028-add-primitives"
      },
      {
        "text": "P3D-029 — Extrude",
        "link": "/bible/specs/p3d-029-extrude"
      },
      {
        "text": "P3D-030 — Multi-Extrude",
        "link": "/bible/specs/p3d-030-multi-extrude"
      },
      {
        "text": "P3D-031 — Inset",
        "link": "/bible/specs/p3d-031-inset"
      },
      {
        "text": "P3D-032 — Bevel",
        "link": "/bible/specs/p3d-032-bevel"
      },
      {
        "text": "P3D-033 — Knife / Cut",
        "link": "/bible/specs/p3d-033-knife-cut"
      },
      {
        "text": "P3D-034 — Loop Cut",
        "link": "/bible/specs/p3d-034-loop-cut"
      },
      {
        "text": "P3D-035 — Subdivide",
        "link": "/bible/specs/p3d-035-subdivide"
      },
      {
        "text": "P3D-036 — Merge",
        "link": "/bible/specs/p3d-036-merge"
      },
      {
        "text": "P3D-037 — Split / Separate",
        "link": "/bible/specs/p3d-037-split-separate"
      },
      {
        "text": "P3D-038 — Mirror simples",
        "link": "/bible/specs/p3d-038-mirror-simples"
      },
      {
        "text": "P3D-039 — Proportional Editing",
        "link": "/bible/specs/p3d-039-proportional-editing"
      },
      {
        "text": "P3D-040 — Sistema de Snap",
        "link": "/bible/specs/p3d-040-sistema-de-snap"
      },
      {
        "text": "P3D-041 — Undo / Redo",
        "link": "/bible/specs/p3d-041-undo-redo"
      },
      {
        "text": "P3D-042 — Asset Browser",
        "link": "/bible/specs/p3d-042-asset-browser"
      },
      {
        "text": "P3D-043 — Busca e filtros de Assets",
        "link": "/bible/specs/p3d-043-busca-e-filtros-de-assets"
      },
      {
        "text": "P3D-044 — Drag & Drop de Assets",
        "link": "/bible/specs/p3d-044-drag-drop-de-assets"
      },
      {
        "text": "P3D-045 — Thumbnails configuráveis",
        "link": "/bible/specs/p3d-045-thumbnails-configuraveis"
      },
      {
        "text": "P3D-046 — Outliner",
        "link": "/bible/specs/p3d-046-outliner"
      },
      {
        "text": "P3D-047 — Visibility / Lock",
        "link": "/bible/specs/p3d-047-visibility-lock"
      },
      {
        "text": "P3D-048 — Inspector / Properties",
        "link": "/bible/specs/p3d-048-inspector-properties"
      },
      {
        "text": "P3D-049 — Transform Inspector",
        "link": "/bible/specs/p3d-049-transform-inspector"
      },
      {
        "text": "P3D-073 — Workspace System",
        "link": "/bible/specs/p3d-073-workspace-system"
      },
      {
        "text": "P3D-074 — Viewport Header contextual",
        "link": "/bible/specs/p3d-074-viewport-header-contextual"
      },
      {
        "text": "P3D-075 — Vertical Tool Toolbar",
        "link": "/bible/specs/p3d-075-vertical-tool-toolbar"
      },
      {
        "text": "P3D-076 — Contextual Tool Shelf",
        "link": "/bible/specs/p3d-076-contextual-tool-shelf"
      },
      {
        "text": "P3D-077 — Menus profissionais",
        "link": "/bible/specs/p3d-077-menus-profissionais"
      },
      {
        "text": "P3D-078 — Painéis retráteis e redimensionáveis",
        "link": "/bible/specs/p3d-078-paineis-retrateis-e-redimensionaveis"
      },
      {
        "text": "P3D-079 — Layout responsivo desktop",
        "link": "/bible/specs/p3d-079-layout-responsivo-desktop"
      },
      {
        "text": "P3D-080 — Status Bar",
        "link": "/bible/specs/p3d-080-status-bar"
      },
      {
        "text": "P3D-081 — Command Palette",
        "link": "/bible/specs/p3d-081-command-palette"
      },
      {
        "text": "P3D-082 — Context Menus",
        "link": "/bible/specs/p3d-082-context-menus"
      },
      {
        "text": "P3D-083 — Tool Properties",
        "link": "/bible/specs/p3d-083-tool-properties"
      },
      {
        "text": "P3D-084 — Design System tokenizado",
        "link": "/bible/specs/p3d-084-design-system-tokenizado"
      },
      {
        "text": "P3D-085 — Temas customizados",
        "link": "/bible/specs/p3d-085-temas-customizados"
      },
      {
        "text": "P3D-086 — Icon Packs",
        "link": "/bible/specs/p3d-086-icon-packs"
      },
      {
        "text": "P3D-087 — Packs oficiais de ícones",
        "link": "/bible/specs/p3d-087-packs-oficiais-de-icones"
      },
      {
        "text": "P3D-088 — Petunia Custom Icons",
        "link": "/bible/specs/p3d-088-petunia-custom-icons"
      },
      {
        "text": "P3D-089 — Sistema completo de traduções",
        "link": "/bible/specs/p3d-089-sistema-completo-de-traducoes"
      },
      {
        "text": "P3D-090 — Keybindings personalizáveis",
        "link": "/bible/specs/p3d-090-keybindings-personalizaveis"
      },
      {
        "text": "P3D-091 — Detecção de conflitos",
        "link": "/bible/specs/p3d-091-deteccao-de-conflitos"
      },
      {
        "text": "P3D-092 — Petunia Default",
        "link": "/bible/specs/p3d-092-petunia-default"
      },
      {
        "text": "P3D-093 — Petunia Simple",
        "link": "/bible/specs/p3d-093-petunia-simple"
      },
      {
        "text": "P3D-094 — Petunia Notebook",
        "link": "/bible/specs/p3d-094-petunia-notebook"
      },
      {
        "text": "P3D-095 — Blender-like",
        "link": "/bible/specs/p3d-095-blender-like"
      },
      {
        "text": "P3D-096 — Blender-like Notebook",
        "link": "/bible/specs/p3d-096-blender-like-notebook"
      },
      {
        "text": "P3D-097 — Maya-like",
        "link": "/bible/specs/p3d-097-maya-like"
      },
      {
        "text": "P3D-098 — 3ds Max-like",
        "link": "/bible/specs/p3d-098-3ds-max-like"
      },
      {
        "text": "P3D-099 — Cinema 4D-like",
        "link": "/bible/specs/p3d-099-cinema-4d-like"
      },
      {
        "text": "P3D-100 — Command System",
        "link": "/bible/specs/p3d-100-command-system"
      },
      {
        "text": "P3D-101 — Tools modulares",
        "link": "/bible/specs/p3d-101-tools-modulares"
      },
      {
        "text": "P3D-102 — Core agnóstico à UI",
        "link": "/bible/specs/p3d-102-core-agnostico-a-ui"
      },
      {
        "text": "P3D-103 — Separação Core / Application / UI",
        "link": "/bible/specs/p3d-103-separacao-core-application-ui"
      },
      {
        "text": "P3D-104 — Headless readiness",
        "link": "/bible/specs/p3d-104-headless-readiness"
      },
      {
        "text": "P3D-105 — Renderer desacoplado da UI",
        "link": "/bible/specs/p3d-105-renderer-desacoplado-da-ui"
      },
      {
        "text": "P3D-106 — Frontends intercambiáveis",
        "link": "/bible/specs/p3d-106-frontends-intercambiaveis"
      },
      {
        "text": "P3D-107 — API cross-language-ready",
        "link": "/bible/specs/p3d-107-api-cross-language-ready"
      },
      {
        "text": "P3D-108 — IDs estáveis",
        "link": "/bible/specs/p3d-108-ids-estaveis"
      },
      {
        "text": "P3D-109 — Events / State synchronization",
        "link": "/bible/specs/p3d-109-events-state-synchronization"
      },
      {
        "text": "P3D-113 — Texturing Nodes simples",
        "link": "/bible/specs/p3d-113-texturing-nodes-simples"
      },
      {
        "text": "P3D-114 — Tooltips completos",
        "link": "/bible/specs/p3d-114-tooltips-completos"
      },
      {
        "text": "P3D-115 — Ajuda contextual ?",
        "link": "/bible/specs/p3d-115-ajuda-contextual"
      },
      {
        "text": "P3D-122 — Architecture Checks",
        "link": "/bible/specs/p3d-122-architecture-checks"
      },
      {
        "text": "P3D-123 — Testes de ferramentas",
        "link": "/bible/specs/p3d-123-testes-de-ferramentas"
      },
      {
        "text": "P3D-125 — Asset/Icon Caching",
        "link": "/bible/specs/p3d-125-asset-icon-caching"
      },
      {
        "text": "P3D-131 — Modal Tool Feedback System",
        "link": "/bible/specs/p3d-131-modal-tool-feedback-system"
      }
    ]
  },
  {
    "text": "P3D: Wave 7: Materials, Texture, UV & Paint (Ativa)",
    "collapsed": true,
    "items": [
      {
        "text": "P3D-050 — Material System",
        "link": "/bible/specs/p3d-050-material-system"
      },
      {
        "text": "P3D-051 — Albedo / Diffuse",
        "link": "/bible/specs/p3d-051-albedo-diffuse"
      },
      {
        "text": "P3D-052 — Normal / Bump",
        "link": "/bible/specs/p3d-052-normal-bump"
      },
      {
        "text": "P3D-053 — Roughness / Glossiness",
        "link": "/bible/specs/p3d-053-roughness-glossiness"
      },
      {
        "text": "P3D-054 — Displacement / Height",
        "link": "/bible/specs/p3d-054-displacement-height"
      },
      {
        "text": "P3D-055 — Paint Workspace",
        "link": "/bible/specs/p3d-055-paint-workspace"
      },
      {
        "text": "P3D-056 — Pixel Brush",
        "link": "/bible/specs/p3d-056-pixel-brush"
      },
      {
        "text": "P3D-057 — Soft Brush",
        "link": "/bible/specs/p3d-057-soft-brush"
      },
      {
        "text": "P3D-058 — Eraser",
        "link": "/bible/specs/p3d-058-eraser"
      },
      {
        "text": "P3D-059 — Fill",
        "link": "/bible/specs/p3d-059-fill"
      },
      {
        "text": "P3D-060 — Color Picker",
        "link": "/bible/specs/p3d-060-color-picker"
      },
      {
        "text": "P3D-061 — Simple Paint Layers",
        "link": "/bible/specs/p3d-061-simple-paint-layers"
      },
      {
        "text": "P3D-062 — Paint de mapas via UV",
        "link": "/bible/specs/p3d-062-paint-de-mapas-via-uv"
      },
      {
        "text": "P3D-063 — UV Workspace",
        "link": "/bible/specs/p3d-063-uv-workspace"
      },
      {
        "text": "P3D-064 — UV Editing básico",
        "link": "/bible/specs/p3d-064-uv-editing-basico"
      },
      {
        "text": "P3D-065 — Integração Paint ↔ UV",
        "link": "/bible/specs/p3d-065-integracao-paint-uv"
      },
      {
        "text": "P3D-132 — Paint Masks / Face & Selection Isolation",
        "link": "/bible/specs/p3d-132-paint-masks-face-selection-isolation"
      },
      {
        "text": "P3D-133 — Decal & Projection Layers",
        "link": "/bible/specs/p3d-133-decal-projection-layers"
      },
      {
        "text": "P3D-134 — Paint Effect Stack",
        "link": "/bible/specs/p3d-134-paint-effect-stack"
      },
      {
        "text": "P3D-140 — Material Shader Profiles & Effects",
        "link": "/bible/specs/p3d-140-material-shader-profiles-effects"
      }
    ]
  },
  {
    "text": "P3D: Wave 8: Import, Export & Delivery",
    "collapsed": true,
    "items": [
      {
        "text": "P3D-068 — Export individual",
        "link": "/bible/specs/p3d-068-export-individual"
      },
      {
        "text": "P3D-069 — Export múltiplo",
        "link": "/bible/specs/p3d-069-export-multiplo"
      },
      {
        "text": "P3D-070 — Batch Export",
        "link": "/bible/specs/p3d-070-batch-export"
      },
      {
        "text": "P3D-071 — Importadores modulares",
        "link": "/bible/specs/p3d-071-importadores-modulares"
      },
      {
        "text": "P3D-072 — Exportadores modulares",
        "link": "/bible/specs/p3d-072-exportadores-modulares"
      },
      {
        "text": "P3D-124 — Testes de import/export",
        "link": "/bible/specs/p3d-124-testes-de-import-export"
      }
    ]
  },
  {
    "text": "P3D: Wave 9: QA, Release & GA Candidate",
    "collapsed": true,
    "items": [
      {
        "text": "P3D-116 — Website de documentação",
        "link": "/bible/specs/p3d-116-website-de-documentacao"
      },
      {
        "text": "P3D-117 — Changelog vivo",
        "link": "/bible/specs/p3d-117-changelog-vivo"
      },
      {
        "text": "P3D-118 — Screenshots atualizados",
        "link": "/bible/specs/p3d-118-screenshots-atualizados"
      },
      {
        "text": "P3D-119 — Referência automática de tokens",
        "link": "/bible/specs/p3d-119-referencia-automatica-de-tokens"
      },
      {
        "text": "P3D-120 — Docs Check",
        "link": "/bible/specs/p3d-120-docs-check"
      },
      {
        "text": "P3D-121 — UI Regression Tests",
        "link": "/bible/specs/p3d-121-ui-regression-tests"
      },
      {
        "text": "P3D-126 — Performance para PCs modestos",
        "link": "/bible/specs/p3d-126-performance-para-pcs-modestos"
      },
      {
        "text": "P3D-127 — No Remesh",
        "link": "/bible/specs/p3d-127-no-remesh"
      },
      {
        "text": "P3D-128 — Sem composição de cenas complexa",
        "link": "/bible/specs/p3d-128-sem-composicao-de-cenas-complexa"
      },
      {
        "text": "P3D-129 — Sem login obrigatório",
        "link": "/bible/specs/p3d-129-sem-login-obrigatorio"
      },
      {
        "text": "P3D-130 — Customização sem quebrar Core",
        "link": "/bible/specs/p3d-130-customizacao-sem-quebrar-core"
      }
    ]
  },
  {
    "text": "P3D: Waves 10 a 13 (Roadmap Pós-GA)",
    "collapsed": true,
    "items": [
      {
        "text": "P3D-066 — Animation Workspace",
        "link": "/bible/specs/p3d-066-animation-workspace"
      },
      {
        "text": "P3D-067 — Animação simples",
        "link": "/bible/specs/p3d-067-animacao-simples"
      },
      {
        "text": "P3D-110 — Lua Plugin System",
        "link": "/bible/specs/p3d-110-lua-plugin-system"
      },
      {
        "text": "P3D-111 — Public Plugin API",
        "link": "/bible/specs/p3d-111-public-plugin-api"
      },
      {
        "text": "P3D-112 — MCP API / Automação",
        "link": "/bible/specs/p3d-112-mcp-api-automacao"
      },
      {
        "text": "P3D-135 — Skeleton & Rig Core",
        "link": "/bible/specs/p3d-135-skeleton-rig-core"
      },
      {
        "text": "P3D-136 — Rig Presets — Humanoid, Quadruped e Multi-Leg",
        "link": "/bible/specs/p3d-136-rig-presets-humanoid-quadruped-e-mult"
      },
      {
        "text": "P3D-137 — Auto-Rig",
        "link": "/bible/specs/p3d-137-auto-rig"
      },
      {
        "text": "P3D-138 — Animation Retargeting / External Compatibility",
        "link": "/bible/specs/p3d-138-animation-retargeting-external-compatibi"
      },
      {
        "text": "P3D-139 — Animation Asset Library",
        "link": "/bible/specs/p3d-139-animation-asset-library"
      },
      {
        "text": "P3D-141 — Internal AI Agent Panel",
        "link": "/bible/specs/p3d-141-internal-ai-agent-panel"
      },
      {
        "text": "P3D-142 — AI-Assisted Modeling Pipeline",
        "link": "/bible/specs/p3d-142-ai-assisted-modeling-pipeline"
      },
      {
        "text": "P3D-143 — Game Engine Integration / Bridge",
        "link": "/bible/specs/p3d-143-game-engine-integration-bridge"
      },
      {
        "text": "P3D-144 — Asset Validator & Game Readiness",
        "link": "/bible/specs/p3d-144-asset-validator-game-readiness"
      },
      {
        "text": "P3D-145 — Collision Authoring",
        "link": "/bible/specs/p3d-145-collision-authoring"
      },
      {
        "text": "P3D-146 — Sockets & Attachment Points",
        "link": "/bible/specs/p3d-146-sockets-attachment-points"
      },
      {
        "text": "P3D-147 — LOD Manager",
        "link": "/bible/specs/p3d-147-lod-manager"
      },
      {
        "text": "P3D-148 — Palette Manager",
        "link": "/bible/specs/p3d-148-palette-manager"
      },
      {
        "text": "P3D-149 — Texture Atlas Builder",
        "link": "/bible/specs/p3d-149-texture-atlas-builder"
      },
      {
        "text": "P3D-150 — Vertex Color Painting",
        "link": "/bible/specs/p3d-150-vertex-color-painting"
      },
      {
        "text": "P3D-151 — Batch Asset Processor",
        "link": "/bible/specs/p3d-151-batch-asset-processor"
      },
      {
        "text": "P3D-152 — Portable Project Package",
        "link": "/bible/specs/p3d-152-portable-project-package"
      },
      {
        "text": "P3D-153 — Tool Presets",
        "link": "/bible/specs/p3d-153-tool-presets"
      },
      {
        "text": "P3D-154 — Command Recipes / Macros",
        "link": "/bible/specs/p3d-154-command-recipes-macros"
      },
      {
        "text": "P3D-155 — Live Asset Link",
        "link": "/bible/specs/p3d-155-live-asset-link"
      }
    ]
  },
  {
    "text": "Adendos Aprovados",
    "collapsed": true,
    "items": [
      {
        "text": "ADENDO-01 — Possíveis futuros módulos sem bloat",
        "link": "/bible/addenda/adendo-01-possiveis-futuros-modulos-sem-bloat"
      },
      {
        "text": "ADENDO-02 — Caminho para uma game engine",
        "link": "/bible/addenda/adendo-02-caminho-para-uma-game-engine"
      },
      {
        "text": "ADENDO-03 — Texturas com efeitos e shaders",
        "link": "/bible/addenda/adendo-03-texturas-com-efeitos-e-shaders"
      }
    ]
  },
  {
    "text": "Fundamentos do Livro Vivo (36 Capítulos)",
    "collapsed": true,
    "items": [
      {
        "text": "01 — Visão, UX e Referências",
        "link": "/bible/foundations/01-visao-ux-referencias"
      },
      {
        "text": "02 — Workflow de Modelagem Shape-First",
        "link": "/bible/foundations/02-workflow-modelagem-shape-first"
      },
      {
        "text": "03 — Geometry Core, Faces e Topologia",
        "link": "/bible/foundations/03-geometry-core-faces-topologia"
      },
      {
        "text": "04 — Combine, Fuse, Weld e Personagens",
        "link": "/bible/foundations/04-combine-fuse-weld-personagens"
      },
      {
        "text": "05 — Viewport, Shading e Modos de Visualização",
        "link": "/bible/foundations/05-viewport-shading-modos-visualizacao"
      },
      {
        "text": "06 — Escopo Essencial: o que entra e o que fica fora",
        "link": "/bible/foundations/06-escopo-essencial"
      },
      {
        "text": "07 — Pesquisa: referências, lacunas e ideias acadêmicas",
        "link": "/bible/foundations/07-pesquisa-referencias-lacunas"
      },
      {
        "text": "08 — Photo Projection, Trace & Project e Lições do Shapr3D",
        "link": "/bible/foundations/08-photo-projection-trace-project"
      },
      {
        "text": "09 — Arquitetura, Princípios de Decisão e Governança Técnica",
        "link": "/bible/foundations/09-arquitetura-governanca-tecnica"
      },
      {
        "text": "10 — Extension API, Plugins e Módulos Oficiais",
        "link": "/bible/foundations/10-extension-api-plugins-modulos"
      },
      {
        "text": "11 — MCP API, Automação e Integração com Agentes de IA",
        "link": "/bible/foundations/11-mcp-api-automacao-agentes"
      },
      {
        "text": "12 — Baseline Funcional, Roadmap e Contrato de Escopo",
        "link": "/bible/foundations/12-baseline-funcional-roadmap-escopo"
      },
      {
        "text": "13 — Contrato para Geração de Documentação pelo Framework",
        "link": "/bible/foundations/13-contrato-geracao-documentacao"
      },
      {
        "text": "14 — Modelagem V1: Cut, Slice, Bevel, Revolve e Simple Sweep",
        "link": "/bible/foundations/14-modelagem-v1-cut-slice-bevel-revolve-sweep"
      },
      {
        "text": "15 — UV, Textura, Projeção e Materiais — Arquitetura Fechada",
        "link": "/bible/foundations/15-uv-textura-projecao-materiais"
      },
      {
        "text": "16 — Documento, Formato de Projeto, Undo, Autosave e Recovery",
        "link": "/bible/foundations/16-documento-formato-undo-recovery"
      },
      {
        "text": "17 — Export, Import, Validação e Pipeline Game-Ready",
        "link": "/bible/foundations/17-export-import-validacao-game-ready"
      },
      {
        "text": "18 — Stack Técnica, Dependências e Fronteiras de Integração",
        "link": "/bible/foundations/18-stack-tecnica-dependencias"
      },
      {
        "text": "19 — Concorrência, Memória, Caches e Performance",
        "link": "/bible/foundations/19-concorrencia-memoria-caches-performance"
      },
      {
        "text": "20 — Testes, Conformance e Qualidade Técnica",
        "link": "/bible/foundations/20-testes-conformance-qualidade"
      },
      {
        "text": "21 — Baseline Funcional e UI V1 Congeladas, Stack Rust Final",
        "link": "/bible/foundations/21-baseline-funcional-ui-v1-stack-rust"
      },
      {
        "text": "22 — Referência de Interface: Análise do Figma Blender UI Redesign",
        "link": "/bible/foundations/22-referencia-interface-figma"
      },
      {
        "text": "23 — Macroarquitetura da Interface Petunia3D",
        "link": "/bible/foundations/23-macroarquitetura-interface"
      },
      {
        "text": "24 — Design System Visual: Tokens, Hierarquia e Estados",
        "link": "/bible/foundations/24-design-system-tokens-estados"
      },
      {
        "text": "25 — Biblioteca de Componentes e Contratos de Interação",
        "link": "/bible/foundations/25-biblioteca-componentes-interacao"
      },
      {
        "text": "26 — Figma → Implementação, Assets e Fundamentos de Acessibilidade",
        "link": "/bible/foundations/26-figma-implementacao-acessibilidade"
      },
      {
        "text": "27 — Stack Rust Canônica: Rust + egui + wgpu",
        "link": "/bible/foundations/27-stack-rust-canonica"
      },
      {
        "text": "28 — Arquitetura Rust, Cargo Workspace e Fronteiras entre Crates",
        "link": "/bible/foundations/28-arquitetura-rust-cargo-crates"
      },
      {
        "text": "29 — Geometry Core, Renderer, UV e Painting na Stack Rust",
        "link": "/bible/foundations/29-geometry-renderer-uv-painting-rust"
      },
      {
        "text": "30 — I/O, Projeto .petunia, Lua Plugins e MCP na Stack Rust",
        "link": "/bible/foundations/30-io-petunia-lua-mcp-rust"
      },
      {
        "text": "31 — Qualidade, IA, CI e Vertical Slice de Conformance da Stack Rust",
        "link": "/bible/foundations/31-qualidade-ia-ci-vertical-slice"
      },
      {
        "text": "32 — ADR: Migração da Baseline Odin para Rust",
        "link": "/bible/foundations/32-adr-odin-para-rust"
      },
      {
        "text": "33 — Biblioteca de Referências Técnicas da Stack Rust",
        "link": "/bible/foundations/33-referencias-tecnicas-rust"
      },
      {
        "text": "34 — Arquitetura Modular Explícita, Rust Safety e Representação em Código",
        "link": "/bible/foundations/34-arquitetura-modular-rust-safety"
      },
      {
        "text": "35 — egui, Petunia Components, UI Adapters e Tooling de Desenvolvimento",
        "link": "/bible/foundations/35-egui-components-adapters-tooling"
      },
      {
        "text": "36 — UI Baseline Final V1, Temas e Plugin Panels",
        "link": "/bible/foundations/36-ui-baseline-temas-plugin-panels"
      }
    ]
  }
];
