[package]
name = "petunia_core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
petunia_mesh = { workspace = true }
petunia_commands = { workspace = true }
petunia_config = { workspace = true }
petunia_project = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
petunia_render = { workspace = true }
tracing = { workspace = true }
slotmap = { workspace = true }
rayon = { workspace = true }
flume = { workspace = true }
schemars = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
criterion = { workspace = true }
insta = { workspace = true }

[[bench]]
name = "core_jobs"
harness = false
