[package]
name = "petunia_module_paint"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
petunia_core = { workspace = true }
petunia_mesh = { workspace = true }
petunia_project = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
